spring.application.name=warehouse

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/freshtrack
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysecretkeymysecretkeymysecretkey
